### ISSUE TITLE
after the update does not work     CreateForm.resolvedWithSomething

### ISSUE THREAD

**Issue by Mirzaliev** [mokkabonna/vue-async-methods#3]
After the upgrade to version 0.8.1 does not work   CreateForm.resolvedWithSomething

**Comment by mokkabonna** [comment]
Can you paste some code? What do you return? I did a change where undefined is considered a empty value. https://github.com/mokkabonna/vue-async-methods/commit/d0eb7a55f3abf49445a85555482be12b453876f4#diff-168726dbe96b3ce427e7fedce31bb0bcR14

So if you return undefined then resolvedWithSomething will be false.

**Comment by mokkabonna** [comment]
Closed due to inactivity.
