### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by 174n** [mokkabonna/vue-async-methods#5]
Here is the method:
```
  asyncMethods:{
    imageSize(url){
      return new Promise((resolve, reject) => {
        let img = document.createElement('img');
        img.src = url;
        img.onload = function(){
          resolve(this.naturalWidth,this.naturalHeight);
        }
      }).then((width,height) => {
        console.log(width,height);
        return {width,height};
      });
    },
  }
```
If I pass parameters in this method like this `{{imageSize(image.url)}}`, I get an error

> [Vue warn]: Error in render function: "TypeError: _vm.imageSize is not a function"

> TypeError: _vm.imageSize is not a function

**Comment by mokkabonna** [comment]
You have to call imageSize.execute

Stated in the docs.

This is because Vue does not support creating reactive properties on functions. https://github.com/vuejs/vue/issues/6648

**Comment by mokkabonna** [comment]
Just wanted you (@Rundik) to know that in the latest version (0.9.1), you can indeed call `imageSize()` instead of `imageSize.execute()`.

**Comment by 174n** [comment]
Good, thank you
