### ISSUE TITLE
Unhandled promise rejection if <catch-async-error> is not used

### ISSUE THREAD

**Issue by abrenneke** [mokkabonna/vue-async-methods#8]
Because the `.catch()` call in `wrapMethod` throws the error again at the end, that means the promise is still rejected. If you use `<catch-async-error>`, then that rejection is caught, but if you don't use the component, then the promise is unhandled and it bubbles up to the console, just like if you use an async method in the normal `methods: {}` property.

Even if you use `options.onError` then the rejection is still unhandled.

It would be nice if you couldn't run into unhandled promise rejections when using this library, but I'm not sure of the exact code changes for that.

**Comment by mokkabonna** [comment]
First of all, sorry for not responding at the time, real life got in the way at the time and it faded in time.

I will consider it. I am currently doing some more work on this library and will rethink some of my initial assumptions. It has been serving me well as is though. I just catch errors from the inital calling function (although not easy without wrapping it in another method if calling directly from the template)

**Comment by abrenneke** [comment]
No worries, my current work doesn't use Vue but I appreciate the reply!
